# Generated by Django 2.1.15 on 2020-06-18 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Gym',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, null=True)),
                ('website', models.URLField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Wod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sched_date', models.DateField(null=True)),
                ('orig_url', models.URLField(max_length=255, null=True)),
                ('workout', models.TextField(null=True)),
                ('coach_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Coach')),
                ('gym_link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizer.Gym')),
            ],
            options={
                'ordering': ['sched_date'],
                'get_latest_by': '-sched_date',
            },
        ),
    ]
