# Generated by Django 2.1.15 on 2020-06-14 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Wod',
            fields=[
                ('workout', models.TextField()),
                ('slug', models.SlugField(help_text='A label for URL config.', max_length=31, unique=True)),
                ('date', models.TextField()),
                ('day', models.FloatField()),
                ('month', models.FloatField()),
                ('year', models.FloatField()),
                ('url', models.URLField(max_length=255)),
                ('day_string', models.TextField()),
                ('month_string', models.TextField()),
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('coach', models.TextField()),
            ],
            options={
                'db_table': 'WOD',
            },
        ),
    ]
