# Generated by Django 2.1.15 on 2020-06-14 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wod',
            name='day',
        ),
        migrations.RemoveField(
            model_name='wod',
            name='month',
        ),
        migrations.RemoveField(
            model_name='wod',
            name='year',
        ),
        migrations.AlterField(
            model_name='wod',
            name='date',
            field=models.DateField(verbose_name='date scheduled'),
        ),
    ]
