# Generated by Django 2.1.15 on 2020-06-14 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0003_auto_20200614_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wod',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='wod',
            name='date',
        ),
        migrations.RemoveField(
            model_name='wod',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='wod',
            name='url',
        ),
        migrations.RemoveField(
            model_name='wod',
            name='workout',
        ),
        migrations.AlterField(
            model_name='wod',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
