# Generated by Django 2.1.15 on 2020-06-14 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0004_auto_20200614_2013'),
    ]

    operations = [
        migrations.AddField(
            model_name='wod',
            name='coach',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='wod',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='wod',
            name='url',
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wod',
            name='workout',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='wod',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
