# Generated by Django 2.1.15 on 2020-06-15 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organizer', '0005_auto_20200614_2019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wod',
            options={'get_latest_by': 'date', 'ordering': ['date']},
        ),
        migrations.AlterModelTable(
            name='wod',
            table=None,
        ),
    ]
